spring:
  kafka:
    consumer:
      bootstrap-servers: 172.30.1.56:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: mongodb://172.30.1.56:27017/test
server:
  port : 8081
